
n_epochs: 200
    
batch_size: 128

device: "cuda"

z_dim: 100

gen_optim: "adam"

crit_optim: "adam"

beta_1: 0.5
        
beta_2: 0.999

gen_lr:  0.0002

crit_lr: 0.0002

display_step: 1000

c_lambda: 10

crit_repeats: 5

data_root: "../../../data/"

data: "CIFAR10"

weight_decay: 0.001