
n_epochs: 200
    
batch_size: 128

device: "cuda"

z_dim: 64

gen_optim: "sgd"

crit_optim: "sgd"

gen_lr:  0.01

crit_lr: 0.01

display_step: 1000

c_lambda: 10

crit_repeats: 5

data_root: "../../../data/"

data: "CIFAR10"

weight_decay: 0.001

momentum: 0.9